/**
 * Writes `src/runtime-sources.generated.ts` from the module bodies in `runtime/src` (LIVE-012).
 * Run `vp run runtime:gen` after editing a runtime `.rs` file; `runtime-sources.test.ts` fails
 * while the generated file is stale.
 */
import { execFileSync } from "node:child_process";
import { readFileSync, readdirSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

/** The crate's own files, which are not runtime modules. */
const CRATE_FILES = new Set(["lib.rs", "tests.rs"]);
const directory = fileURLToPath(new URL("../runtime/src/", import.meta.url));
export const runtimeModuleNames = (): ReadonlyArray<string> =>
  readdirSync(directory)
    .filter((file) => file.endsWith(".rs") && !CRATE_FILES.has(file))
    .map((file) => file.slice(0, -".rs".length))
    .sort();
/** A module body as emitters inline it: LF line endings, whatever the checkout uses. */
export const runtimeModuleText = (name: string): string =>
  readFileSync(`${directory}${name}.rs`, "utf8").replaceAll("\r\n", "\n");

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const entries = runtimeModuleNames()
    .map((name) => `  ${name}:\n    ${JSON.stringify(runtimeModuleText(name))},`)
    .join("\n");
  const output = fileURLToPath(new URL("../src/runtime-sources.generated.ts", import.meta.url));
  writeFileSync(
    output,
    `// Generated by scripts/runtime-sources.ts from runtime/src/*.rs (LIVE-012). Do not edit.\n` +
      `/** Static runtime module bodies, keyed by module name. */\n` +
      `export const RuntimeSources = {\n${entries}\n} as const;\n`,
  );
  // The repository formatter picks each string's quotes; formatting here keeps `vp check` clean.
  execFileSync("vp", ["fmt", output], { stdio: "inherit", shell: process.platform === "win32" });
}
