// Generated by reffect's milestone 8B translator from foldkit@0.165.0 examples/ssr (packages/reffect/tests/fixtures/upstream-ssr). Do not edit:
// regenerate it from the pinned source instead (docs/research/ssr-codemod.md).
import { defineMessageUnion } from "foldkit/message";
import { R } from "../../packages/reffect/src/authoring.ts";
import type { Expr, Value } from "../../packages/reffect/src/kernel.ts";

const H = R.Html;
export const Model = R.Struct({
  count: R.Number,
  renderedAt: R.String,
  renderedOn: R.Literals(["Server", "Client"]),
});
export const Flags = R.Struct({
  initialCount: R.Number,
  renderedAt: R.String,
  renderedOn: R.Literals(["Server", "Client"]),
});
export const Message = defineMessageUnion({
  ClickedDecrement: {},
  ClickedIncrement: {},
  CompletedPersistCount: {},
});
export const PageRequest = R.Struct({ method: R.String, cookie: R.String, now: R.DateTime.Utc });
const init = (flags: Expr<Value<typeof Flags>>) =>
  Model.make({
    count: R.Struct.get(flags, "initialCount"),
    renderedAt: R.Struct.get(flags, "renderedAt"),
    renderedOn: R.Struct.get(flags, "renderedOn"),
  });
const view = (model: Expr<Value<typeof Model>>) =>
  H.Document.make({
    title: R.String.concat(
      R.String.literal("Count "),
      R.String.fromNumber(R.Struct.get(model, "count")),
    ),
    body: H.div(
      [H.Class("min-h-screen bg-white flex flex-col items-center justify-center gap-6 p-6")],
      [
        H.h1([H.Class("text-2xl font-semibold text-gray-800")], ["Server-rendered counter"]),
        H.p(
          [H.Id("count"), H.Class("text-6xl font-bold text-gray-800")],
          [R.String.fromNumber(R.Struct.get(model, "count"))],
        ),
        H.div(
          [H.Class("flex flex-wrap justify-center gap-4")],
          [
            H.button(
              [
                H.Type("button"),
                H.Tabindex(0),
                H.OnClick(H.message(Message.ClickedDecrement, {})),
                H.Class("bg-black text-white hover:bg-gray-700 px-4 py-2 transition"),
              ],
              ["-"],
            ),
            H.button(
              [
                H.Type("button"),
                H.Tabindex(0),
                H.OnClick(H.message(Message.ClickedIncrement, {})),
                H.Class("bg-black text-white hover:bg-gray-700 px-4 py-2 transition"),
              ],
              ["+"],
            ),
          ],
        ),
        H.p(
          [H.Id("provenance"), H.Class("text-sm text-gray-500")],
          [
            R.String.concat(
              R.String.concat(
                R.String.concat(
                  R.String.literal("Rendered on the "),
                  R.Literals(["Server", "Client"]).text(R.Struct.get(model, "renderedOn")),
                ),
                R.String.literal(" at "),
              ),
              R.Struct.get(model, "renderedAt"),
            ),
          ],
        ),
        H.p(
          [H.Class("text-sm text-gray-500 max-w-md text-center")],
          [
            "The count persists in a cookie. Reload the page and the server renders your latest count into the HTML before any JavaScript runs.",
          ],
        ),
        H.div(
          [H.Id("parse-equivalence"), H.Class("hidden")],
          [
            H.select(
              [H.Id("equivalence-select"), H.Value("a")],
              [H.option([H.Value("a")], ["A"]), H.option([H.Value("a"), H.Selected(true)], ["B"])],
            ),
            H.pre([H.Id("equivalence-pre"), H.InnerHTML("\nleading")]),
            H.textarea([H.Id("equivalence-textarea"), H.Value("\nleading")]),
          ],
        ),
      ],
    ),
  });
/** The entry's renderPage: what the native host answers each page request with. */
export const page = R.fn([PageRequest], H.Entry, (request) =>
  R.Match.bool(
    R.String.eq(R.Struct.get(request, "method"), R.String.literal("OPTIONS")),
    H.responded({
      status: R.Number.literal(204),
      headers: R.Array.make(
        H.Header.make({
          name: R.String.literal("allow"),
          value: R.String.literal("GET, HEAD, POST, PUT, PATCH, DELETE, OPTIONS"),
        }),
      ),
    }),
    H.rendered(
      H.renderToString(
        { init, view },
        {
          buildId: "ssr-8b",
          flags: Flags.make({
            initialCount: R.Option.getOrElse(
              R.Option.filter(
                R.Option.flatMap(
                  R.Record.get(
                    R.Cookies.parseHeader(R.Struct.get(request, "cookie")),
                    R.String.literal("foldkit-ssr-count"),
                  ),
                  (v1) => R.Number.parse(v1),
                ),
                (v2) => R.Number.isSafeInteger(v2),
              ),
              () => R.Number.literal(0),
            ),
            renderedAt: R.DateTime.formatIso(R.Struct.get(request, "now")),
            renderedOn: R.Literals(["Server", "Client"]).literal("Server"),
          }),
        },
      ),
      {
        headers: R.Array.make(
          H.Header.make({
            name: R.String.literal("cache-control"),
            value: R.String.literal("private, no-store"),
          }),
          H.Header.make({ name: R.String.literal("vary"), value: R.String.literal("cookie") }),
          H.Header.make({
            name: R.String.literal("x-content-type-options"),
            value: R.String.literal("nosniff"),
          }),
        ),
      },
    ),
  ),
);
